name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.3.3
  file_picker: 5.3.3
  get: 4.6.6
  oktoast: 3.3.1
  path_provider: 2.1.0
  log_wrapper:
    git:
      url: https://github.com/flutter-packagist/log_wrapper.git
      ref: 1.0.2
  mvc:
    git:
      url: https://github.com/flutter-packagist/mvc.git
      ref: 1.0.6
  network:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
