name: network
description: Wrapper network request library for dio.
version: 1.1.0
homepage: https://github.com/flutter-packagist/network

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dio: ^5.3.3
  log_wrapper:
    version: 1.0.0
    hosted:
      name: log_wrapper
      url: http://192.168.8.75:4000/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
